[package]
name = "app"
version = "1.0.0"
authors = ["The Teaclave Authors"]
edition = '2018'

[dependencies]
sgx_types = { rev = "v1.1.1", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_urts = { rev = "v1.1.1", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
